### ISSUE TITLE
Max Container capacity increase loot amount in chests.

### ISSUE THREAD

**Issue by Seljuck-Cannith** [sinai-dev/StrandedDeep.Mods#1]
Hello

First of all thanks for a great and WORKING modpack for Stranded Deep. I really love it , especially map. That is something that I was looking for, for a very long time. Thanks for that. 
Secondly I want to ask you if you would be able to add a setting to "Containers Tweaks" that decrease amount of loot in chests when Max container capacity is active? Because right now if I enable max capacity setting, all crates, chests, lockboxes etc gives much more loot .. they are almost full of stuff.. and that feels almost like cheating.

It should be possible i think.  I saw at least one mod that have that setting, unfortunately it's no longer working as intended.. probably due to compatibility issue with current game version..

Best regards
~Sel

**Comment by sinai-dev** [comment]
Hey, thanks for the kind words. Yeah I agree the extra loot is pretty overpowered, was going to add that when I remembered, thanks for reminding me. Added in latest version.
